name: Deploy sanity
on:
    push:
        branches: [main]
jobs:
    Deploy-Sanity:
        runs-on: ubuntu-latest
        name: Deploy Sanity
        steps:
          - uses: actions/checkout@v2
          - uses: sanity-io/github-action-sanity@v0.2-alpha
            env:
              SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
            with:
              args: deploy


