name: Deploy sanity
on:
    push:
        branches: [main]
jobs:
    Deploy-Sanity:
        runs-on: ubuntu-latest
        name: Deploy Sanity
        steps:
          - uses: actions/checkout@v2
          - name: Install dependencies
            run: npm ci
          - name: Install the Sanity CLI
            run: npm install -g @sanity/cli
          -name: Deploy the studio
            run: sanity deploy
            env:
              SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}


